[#if ctx.specialColumnManager?has_content]
    [#--  IN CASE YOU NEED TO FORCE DIFFERENT COLUMN MANGER  --]
    [#include ctx.specialColumnManager]
[#else]
    [#--  CLASS NAMES FOR EACH LAYOUT  --]
    [#assign max1 = "col-xs-12"]
    [#assign max2 = "col-md-6"]
    [#assign max2_double = "col-xs-12"]
    [#assign max3 = "col-sm-4"]
    [#assign max3_double = "col-sm-8"]
    [#assign max4 = "col-sm-6 col-md-3"]
    [#assign max4_double = "col-md-6"]
    [#assign max4_triple = "col-md-9"]
    [#assign max6 = "col-xs-6 col-sm-4 col-md-2"]
    [#assign max6_double = "col-sm-8 col-md-4"]
    [#assign max6_triple = "col-md-6"]
    
    [#--  SIZEUP if need  --]
    [#assign sizeUp = ""]
    [#if content.sizeUp?has_content]
        [#assign sizeUp = content.sizeUp]
    [/#if]
    
    [#assign renderer = "half"]
    
    [#--  MAX COLUMNS, default is 4  --]
    [#assign maxCols = "4"]
    [#if ctx.maxCols?has_content]
        [#assign maxCols = ctx.maxCols]
    [/#if]
    
    
    [#if maxCols = "1"]
    
        [#assign colDivClass = max1]
        [#assign renderer = "full"]
    
    [#elseif maxCols = "inGroup"]
    
        [#assign colDivClass = ""]
        [#assign renderer = "full"]
    
    [#elseif maxCols = "2"]
    
        [#if sizeUp = "double"]
            [#assign colDivClass = max2_double]
            [#assign renderer = "full"]
        [#elseif sizeUp = "triple"]
            [#assign colDivClass = max2_double]
            [#assign renderer = "full"]
        [#else]
            [#assign colDivClass = max2]
            [#assign renderer = "half"]
        [/#if]
        
    [#elseif maxCols = "3"]
    
        [#if sizeUp = "double"]
            [#assign colDivClass = max3_double]
            [#assign renderer = "full"]
        [#elseif sizeUp = "triple"]
            [#assign colDivClass = max3_double]
            [#assign renderer = "full"]
        [#else]
            [#assign colDivClass = max3]
            [#assign renderer = "half"]
        [/#if]
        
    [#elseif maxCols = "6"]
    
        [#if sizeUp = "double"]
            [#assign colDivClass = max6_double]
            [#assign renderer = "half"]
        [#elseif sizeUp = "triple"]
            [#assign colDivClass = max6_triple]
            [#assign renderer = "half"]
        [#else]
            [#assign colDivClass = max6]
            [#assign renderer = "small"]
        [/#if]
        
    [#else] [#--  default: 4  --]
    
        [#if sizeUp = "double"]
            [#assign colDivClass = max4_double]
            [#assign renderer = "half"]
        [#elseif sizeUp = "triple"]
            [#assign colDivClass = max4_triple]
            [#assign renderer = "full"]
        [#else]
            [#assign colDivClass = max4]
            [#assign renderer = "half"]
        [/#if]
    [/#if]
[/#if]